"""Generated by tools/make_hand_words.py - edit that, not this.

Common English words typed with one hand on qwerty, most common
first. Sources: Monkeytype english_10k / english_25k for
frequency, dwyl/english-words (public domain) as the dictionary.
"""

LEFT = """
be are at as was we free see web get were date state data add after best
read set great car address states area reserved based case care access water
art text rate save card west estate start better test server cart staff
street tax act red rates create few east age fax star areas cards added
trade cars arts database average ever bad fast fact far cases face effects
created base started bar effect gas career sat degree wed bed safe feed sea
award tree extra rated stars feet abstract greater fees grade rest stage
race target debt sets awards fee reader gets fat saw dead agree careers cat
gear tests edge waste bag servers dates tags serve gave facts reserve draft
readers taxes cast stated stats served tag sweet bear feeds faster secret
assets beta bags wear rare bars addresses eat seat referred agreed degrees
fear wars beat tea trees dress refer bass stress aware greatest raw ages
affect affected wet wave acts crafts debate starts bears treated draw babe
crew tested rear exact databases avatar dear vat beer saved treat reverse
tab regard beds asset severe aged seed grace gate taste excess seats era
garage craft cafe addressed waters bet streets cats desert arcade awarded
dad creates faces grades radar adds ear ward beast targets serves brass
acres secrets ease tabs extras bread decrease reserves reads exceed sad
regards grass egg dated stages assess gadgets wage arc texts reed vast
refers trace tee beef cad seeds targeted decade adverse waves extract
detected decades eggs cassette beads fewer drew tagged gates grew rat sees
saver reset deer faced starter races cedar sacred tears cab drag arrested
assessed accessed wages beaver bases bee rats dresses fever bare rebate
aggregate affects detect fastest beverage screw watt trades edges reward
sage bat breed cave arrest decreased grab attract terrace verse watts
rewards ears agrees defects fate breeds actress grave saves regarded defeat
tar retreat estates acre reef deserve garbage dare wax reggae beats cage
gazette beverages rage fears dressed trader badge fare ate tract afterwards
deaf rebates vertex tear freeze crest deferred draws advert feat ware seas
brave savage fares safer sewer treats exceeds traders bead scattered drawer
defect wade cares extracted crafted defeated sweat breeze debates freezer
acted stressed dessert traded restart gases debts attracted fest deed eager
feast react vase exceeded cease deserves screws averages straw carved
extracts decreases beavers crab sweater beware verb desserts regret deceased
deeds racer bets fade tastes gag carts wasted reversed graves feeder wastes
gadget webs traces weaver creed faxes adverts decree assert teas acetate
brew ares eraser gears waft tweed eastwards carder grater aster cascade
fewest refract wedge baste redacted sedate arrears raze rearward wafer
scarred cassava swerve regress abstracted bated aftertaste begat wets egress
stab cedes braced baddest tart twee sweets stew tweet tester screwed
abstracts ester zest screed drab abscess zebra fader redstart beers crate
dredge badder aggravated barf beet craze fracas drat saber tweezers tease
watercress desecrate decease wetted vertebra egged reefer excrete raster
sass berate crags ferret tatters tsar vertebrate barrage taster testes frees
grader aggravates swab secede effete accesses bats revert crease beeswax
egad serfs traverse secrete daze carat staggers deface teat grebe ersatz
scabbard debase teeter crass crag tarts beget cadet fated tress waver braces
sewage caterer cede abet badger deter sewed czar seaweed stag erase carer
fester retrace eater carafe faze reefs crater fevered sextet crevasse
devastate cabaret settee waster scat abraded wards aggregates gaga cravat
earwax beret wastage dregs wrest abetted breve referee rafter creased cress
cataract wester etcetera rave terra bereft caws abate secretes aggravate
taffeta weave veer seabed farad attest tweeter adage garter revere errata
geezer batter sated graze aerate taters serf brat recreate reeded barter
cadaver gaffer agate adverbs gaff scree detract cadre deft stagger beater
carve accede reassess aerated tattered caber bazaar fazed barb segregated
verbs wader adverb abracadabra attested abaca tater gage stewed gaffe bard
staffs brewed brats seafarer sear craters tabard razz retracted refereed
warts tare gazetteer scab scarab swat breads evade aces facade ravages
versed detest crested fete retread abated wart avast exaggerate stewardess
tees brewer baccarat breeder weft recede swagger carver bras grabber
federate stave retract carcass caster adder saga deadbeat cater starred
webbed segregate addressee fetter strafe defer crabs exacerbate dreads
vacate swag regatta vats redder tartar sarge fretted warder reeve seer
grease verve agave steerage wearer recast daft feta federated ravage abbess
degrade egret sedge gasses caveat sever terse stewardesses debater tsetse
brad zeta eaves raver dresser darts graft deserter
""".split()

RIGHT = """
in on you no up only link him join look million upon oil union hi inn hill
opinion pop pool minimum jump pink null moon hip ink pin kill holy poll hop
loop milk pull pump joy ill mill pill punk lookup lion hook nylon noon polo
lip hull puppy junk onion nil pony imply pupil noun monopoly monk pumpkin
plump killjoy loom pinky polio phylum polyphony kimono lumpy hoop poppy
knoll jumpy homily hulk loin lupin ploy nippy plop mummy mull lull hunk
poplin mommy plonk puny uphill loony lolly nymph milky homonym kiln limo
mink unholy limply juju plum kink polyp pylon hump hippo oily mini pulp kilo
loon moony holly lymph honk pillion yolk minion lollipop
""".split()
