"""Rebuild minitype/words/hand_words.py, the built-in one-hand word lists.

A word is kept when it:
  - is in Monkeytype's English 10k or 25k list, so it's reasonably common;
  - is also in dwyl/english-words (public domain), so it's a dictionary word
    and not an abbreviation that slipped into the frequency list;
  - appears at least MIN_COUNT times in Peter Norvig's web word counts
    (count_1w.txt). The 25k list isn't in frequency order, so without this
    its tail is archaic words like "bargee" and "zareba". The counts are
    only used to filter; none of them end up in the app;
  - isn't in BLOCKED: names and places that the frequency lists carry in
    lowercase ("texas", "july"), and slurs or crude words. The list was
    made by reading every generated word; re-check new output the same way;
  - can be typed with one hand on qwerty (the app re-filters for other
    layouts at run time).

Run from the repo root:  python tools/make_hand_words.py
"""

import json
import os
import urllib.request

MT = ("https://raw.githubusercontent.com/monkeytypegame/monkeytype/master"
      "/frontend/static/languages/")
SOURCES = [MT + "english_10k.json", MT + "english_25k.json"]
DICTIONARY = "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"
COUNTS = "https://norvig.com/ngrams/count_1w.txt"
MIN_COUNT = 40_000
BLOCKED = set("""
texas greece arab carter essex tex qatar warsaw ferrara ceres vesta veda deva
brett weber descartes ezra everest teresa aztec bret berber accra greg dewar
asgard zebedee serb swede watergate dexter crete caaba esdras caracas vega
tatar adar abas bates babs cate tara sade dada sabbat safar rabat cree bree
gaea abba araba wagga adat vara sata erse czardas easter
july ohio honolulu yukon juno jill molly phillip hopi lynn loki nippon lulu
pooh moll moho phon
injun poon yoni pimp kinky fart farts sexed sext bawd defecate
acct def ad ads ho brrr redd fard vext tex babes castrate
abbe sacra rete sard cade daff gree rede fess rase bate dette trave fere afer
tasse sett bever batt dater cager testa cert exec frag caff tedder sacre
sward raga arras attar cadastre avers vert erst brassard tetrad evert stager
debar bast wrasse bracer stater scad scads darter berg caret dace facer abed
tzar barre stat grad frat swart tessera tetra ewers ewer craw aver adze
tracer regarder accreted acceded tractate tartrate verger sabre tasse
pook hullo lino moulin holm pion poly mono punkin minim hypo ilium loll lippy
""".split())
LEFT = set("qwertasdfgzxcvb")
RIGHT = set("yuiophjklnm")
OUT = os.path.join(os.path.dirname(__file__), "..", "minitype", "words", "hand_words.py")


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def main():
    common = []
    for url in SOURCES:
        common += json.loads(fetch(url))["words"]
    dictionary = set(fetch(DICTIONARY).split())
    counts = {}
    for line in fetch(COUNTS).splitlines():
        word, _, n = line.partition("\t")
        counts[word] = int(n or 0)
    seen, words = set(), []
    for w in common:                     # keeps frequency order, 10k first
        w = w.lower()
        if w.isalpha() and len(w) >= 2 and w in dictionary and w not in BLOCKED \
                and counts.get(w, 0) >= MIN_COUNT and w not in seen:
            seen.add(w)
            words.append(w)
    left = [w for w in words if set(w) <= LEFT]
    right = [w for w in words if set(w) <= RIGHT]

    def block(name, ws):
        lines, line = [], ""
        for w in ws:
            if len(line) + len(w) + 1 > 76:
                lines.append(line)
                line = ""
            line += (" " if line else "") + w
        lines.append(line)
        return f'{name} = """\n' + "\n".join(lines) + '\n""".split()\n'

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write('"""Generated by tools/make_hand_words.py - edit that, not this.\n\n'
                "Common English words typed with one hand on qwerty, most common\n"
                "first. Sources: Monkeytype english_10k / english_25k for\n"
                "frequency, dwyl/english-words (public domain) as the dictionary.\n"
                '"""\n\n')
        f.write(block("LEFT", left) + "\n" + block("RIGHT", right))
    print(f"left {len(left)}  right {len(right)}  -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
